export default (connection, DataTypes) => {
  return connection.define(
    "hotoschedules",
    {
      checklistType: DataTypes.INTEGER,
      planId: DataTypes.INTEGER,
      planOrderNumber: DataTypes.STRING,
      scheduleDate: DataTypes.DATE,
      facilityId: DataTypes.INTEGER,
      facilityName: DataTypes.STRING,
      assetCategoryId: DataTypes.INTEGER,
      assetCategoryName: DataTypes.STRING,
      assetId: DataTypes.INTEGER,
      assetName: DataTypes.STRING,
      ptwId: DataTypes.INTEGER,
      ptwTitle: DataTypes.STRING,
      ptwById: DataTypes.INTEGER,
      ptwStatus: DataTypes.INTEGER,
      ptwAttachedAt: DataTypes.DATE,
      startFlag: DataTypes.INTEGER,
      executedById: DataTypes.INTEGER,
      executedStatus: DataTypes.INTEGER,
      executedDate: DataTypes.DATE,
      approvedById: DataTypes.INTEGER,
      approvedStatus: DataTypes.INTEGER,
      approvedReccomendation: DataTypes.TEXT,
      approvedDate: DataTypes.DATE,
      rejectedById: DataTypes.INTEGER,
      rejectedStatus: DataTypes.INTEGER,
      rejectedReccomendation: DataTypes.TEXT,
      rejectedDate: DataTypes.DATE,
      createdDate: DataTypes.DATE,
      scheduleCreatedByEmpId: DataTypes.INTEGER,
      scheduleUpdatedDate: DataTypes.DATE,
      scheduleUpdatedByEmpId: DataTypes.INTEGER,
      auditeeEmpId: DataTypes.INTEGER,
      auditorEmpId: DataTypes.INTEGER,
      prevScheduleId: DataTypes.INTEGER,
    },
    {
      timestamps: false,
    }
  );
};
